theme: jekyll-theme-minimal
title: From Hops to Glass
description: A Comprehensive Analysis of Beer Characteristics
show_downloads: false
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
  - title: Cluster0
    url: clusters/cluster0

plugins:
  - jekyll-livereload

livereload:
  enabled: true
