theme: jekyll-theme-minimal
title: From Hops to Glass
description: A Comprehensive Analysis of Beer Characteristics
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
